### ISSUE TITLE
CMake version

### ISSUE THREAD

**Issue by aytekinar** [JuliaPackaging/CMake.jl#10]
Is there a specific reason for

> ... a modern version of CMake (3.7.2, instead of the Ubuntu 14.04 default of 2.8.12) ...

I mean, can we have the latest version or at least `3.9.0` for CMake? `3.9.0` is the version that has [introduced][1] the `find_dependency` macro that passes all the arguments to `find_package`, which simplifies a lot of dependency management in config files of cmake-generated libraries. I can work on a PR if simply bumping the package version introduces some trouble.

Thank you!

[1]: https://gitlab.kitware.com/cmake/cmake/blob/v3.9.0/Modules/CMakeFindDependencyMacro.cmake#L10

**Comment by stevengj** [comment]
3.7.2 was the latest version around the time this package (or rather, [its predecessor](https://github.com/JuliaPackaging/CMakeWrapper.jl)) was created.    I agree that it's become a bit out of date, and a PR to update to a newer version would be welcome.

Any version that is backward-compatible with 3.7 would be fine — hopefully CMake mostly follows the semver spec, which would make any 3.x release okay?

**Comment by aytekinar** [comment]
Thank you for your fast response. I have created the PR. Let's see if the tests will pass in different platforms.

> Any version that is backward-compatible with 3.7 would be fine — hopefully CMake mostly follows the semver spec, which would make any 3.x release okay?

According to what I know, that is correct --- semver is followed by CMake. But with a brief search on the internet, I can only provide [cmake-policies][1] (first paragraph) as a somewhat proof of the statement.

[1]: https://cmake.org/cmake/help/v3.0/manual/cmake-policies.7.html
