### ISSUE TITLE
doesn't support building on FreeBSD

### ISSUE THREAD

**Issue by RobvanW** [JuliaPackaging/CMake.jl#15]
- using FreeBSD 12.0 - stable  
- path to FreeBSD cmake is /usr/local/bin

As FreeBSD is not in the build.jl file function `process` to force CMake.jl to build, I had to resort to changing it's build.jl file as follows: 
```
# avoid process to be called
#run(process) 

# change /bin to /local/bin
open(joinpath(dirname(@__FILE__), "deps.jl"), "w") do f
    write(f, """
const cmake = "$(escape_string(joinpath(prefix, "/local/bin", binary_name)))"
```
There certainly is a more elegant way to achieve the building of CMake.jl to succeed on FreeBSD. I hope someone can incorporate this.

Cheers,
Rob

**Comment by stevengj** [comment]
Should be fixed by #16.
