### ISSUE TITLE
cleanup after build

### ISSUE THREAD

**Issue by asbisen** [JuliaPackaging/CMake.jl#19]
currently CMake.jl build process leaves the downloaded tarball along with extracted source under deps/downloads. This leaves ~200MB of data that could be cleaned up after successful build. 

Although not much but this becomes important for individuals building Docker container for example.

**Comment by stevengj** [comment]
It would be pretty reasonable to do `rm(joinpath(basedir, "downloads"), recursive=true)` at the end of the installation.

**Comment by stevengj** [comment]
Oh wait, on some systems there is a symlink to stuff in `downloads` … and it might refer to some files in the `downloads` directory.  So we may not be able to remove the whole directory.
