### ISSUE TITLE
Redundant binary copies

### ISSUE THREAD

**Issue by jebej** [JuliaPackaging/CMake.jl#30]
At least on windows, there are three copies of cmake on disk: the downloaded archive and the extracted archive in `deps\downloads`, and an other extracted copy found in  `deps\usr`.

**Comment by stevengj** [comment]
On non-Windows systems we use a symlink, but I get your point that we could set `const cmake` to point to the `cmake` executable in the extracted archive itself rather than moving it anywhere.  And we could delete the downloaded archive.

**Comment by jebej** [comment]
Could the archive simply be extracted in the right place to begin with? It's unclear to me where this happens in `build.jl`

**Comment by stevengj** [comment]
Actually, it looks like the [downloaded archive is already deleted](https://github.com/JuliaPackaging/CMake.jl/blob/master/deps/build.jl#L88).

**Comment by jebej** [comment]
I don't see this happening anymore.
